# Feature Encoding

## Numerical Variables are Scaled or Normalized

## Categorical Variables are Encoded

## Types of Encoding
1. One Hot Encoding
2. Label Encoding
3. Ordinal Encoding
4. Helmert Encoding
5. Binary Encoding
6. Frequency Encoding
7. Mean Encoding
8. Weight of Evidence Encoding
9. Probability Ratio Encoding
10. Hash Encoding
11. Target Encoding
12. Leave One Out Encoding
13. CatBoost Encoding
14. James-Stein Encoding
15. M-estimator Encoding
16. Thermometer Encoder
17. Polynomial Encoder
18. BaseN Encoding
19. Backward Difference Encoding


In [1]:
# Import libraries for one hot encoding
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder


In [2]:
# creata a dataframe
data = pd.DataFrame({'A': ['a', 'b', 'a'], 'B': ['b', 'a', 'c']})
print(data)

   A  B
0  a  b
1  b  a
2  a  c


In [5]:
# create an instance of one-hot-encoder and save the encoded data in a new column

encoder = OneHotEncoder()
encoder.fit(data)
encoded_data = encoder.transform(data).toarray()
print(encoded_data)
print(encoder.get_feature_names_out())


[[1. 0. 0. 1. 0.]
 [0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 1.]]
['A_a' 'A_b' 'B_a' 'B_b' 'B_c']


In [6]:
# use label encoding and save enoded data in a new column
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
data['A_encoded'] = label_encoder.fit_transform(data['A'])
data['B_encoded'] = label_encoder.fit_transform(data['B'])
print(data)

   A  B  A_encoded  B_encoded
0  a  b          0          1
1  b  a          1          0
2  a  c          0          2


In [7]:
# use ordinal encoding and save enoded data in a new column
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()
data['A_encoded'] = ordinal_encoder.fit_transform(data[['A']])
data['B_encoded'] = ordinal_encoder.fit_transform(data[['B']])
print(data)


   A  B  A_encoded  B_encoded
0  a  b        0.0        1.0
1  b  a        1.0        0.0
2  a  c        0.0        2.0
